name: planner_messenger
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+3

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  s_state: ^0.0.1+6
  flutter_spinkit: ^5.2.0
  get: ^4.6.6
  bottom_sheet: ^4.0.1
  google_fonts: 6.1.0
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  socket_io_client: ^2.0.3+1
  flex_color_scheme: ^7.3.1
  photo_gallery: ^2.1.1
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  file_picker: ^5.2.10
  transparent_image: ^2.0.1
  #super_context_menu: ^0.1.0
  swipe_to: ^1.0.6
  multi_image_layout: ^0.1.1
  #indexed_list_view: ^3.0.2
  #scrollable_positioned_list: ^0.3.8
  #flutter_list_view: ^1.1.23
  #pull_to_refresh: ^2.0.0
  #reverse_loadmore: ^1.0.0
  #image_editor: ^1.4.0
  #hsluv: ^1.1.3
  flutter_brand_palettes: ^0.5.1
  #flutter_hsvcolor_picker: ^1.5.0
  path: ^1.9.0
  open_filex: ^4.4.0
  path_provider: ^2.1.2
  syncfusion_flutter_gauges: ^25.1.37
  filesystem_picker: ^4.1.0
  #flutter_webrtc: ^0.9.48+hotfix.1
  #flutter_webrtc_wrapper: ^1.0.2
  #sdp_transform: ^0.3.2
  #mediasoup_client_flutter: ^0.8.5
  #protoo_client: ^0.3.3
  #random_string: ^2.3.1

  #flutter_bloc: ^7.0.0
  #equatable: ^2.0.5
  #expandable_bottom_sheet: ^1.1.1+1
  firebase_core: ^2.29.0
  firebase_messaging: ^14.8.1
  flutter_local_notifications: ^17.0.1
  super_context_menu: ^0.7.3
  device_info_plus: ^9.1.2
  #scroll_to_index: ^3.0.1
  readmore: ^2.2.0
  scrollable_positioned_list_extended: ^0.3.9
  flutter_image_compress: ^2.2.0
  flutter_app_badger: ^1.5.0
  flutter_dynamic_icon: ^2.1.0
  shimmer: ^3.0.0
  video_call:
    git:
      url: https://github.com/sbaskoy/video_call
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  rename_app: ^1.3.2
  flutter_native_splash: ^2.4.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  image: "assets/logo.jpg"

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/coca_images/
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
